"""
Milestone 2.5: Preliminary marker-score annotation of Leiden clusters.

Purpose
-------
This script adds a first-pass biological interpretation layer to the
unsupervised Leiden clusters generated in Milestone 2.

At this stage, Leiden clusters are only computational labels such as:
    0, 1, 2, ..., 11

This script helps convert those cluster IDs into provisional biological
labels such as:
    Tumor epithelial
    Stromal/CAF
    Immune-enriched
    Myeloid/macrophage
    Endothelial/vascular
    Proliferative

Important
---------
These are preliminary labels only.

They are based on known marker-gene signature scores, not formal
cluster-specific differential expression. The more rigorous annotation step is
performed later in:

    src/analysis/03_marker_gene_analysis.py

Analysis choices and alternatives
---------------------------------
This script uses Scanpy's `sc.tl.score_genes`, which computes a relative
signature score for each spot based on a marker gene list.

Alternative approaches that could be explored later include:
    - AUCell-style gene set activity scoring
    - ssGSEA / GSVA-style pathway scoring
    - decoupler-based pathway or transcription factor activity scoring
    - Cell-type deconvolution using a single-cell RNA-seq reference
    - Manual pathologist-informed annotation from H&E morphology
    - Spatial neighborhood enrichment using Squidpy
"""

from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd
import scanpy as sc


# ---------------------------------------------------------------------
# Project paths
# ---------------------------------------------------------------------
# `__file__` points to this script:
#   src/analysis/02b_label_clusters_with_marker_scores.py
#
# `parents[2]` moves up two directories:
#   src/analysis/ -> src/ -> project root
PROJECT_ROOT = Path(__file__).resolve().parents[2]

# Input AnnData object produced by Milestone 2.
# This object should already contain:
#   - normalized/log-transformed expression
#   - PCA coordinates
#   - UMAP coordinates
#   - Leiden cluster assignments stored in `adata.obs["leiden_r06"]`
INPUT_H5AD = (
    PROJECT_ROOT
    / "data"
    / "processed"
    / "visium_human_breast_cancer_processed_clustered.h5ad"
)

# Output AnnData object after adding preliminary marker-score labels.
OUTPUT_H5AD = (
    PROJECT_ROOT
    / "data"
    / "processed"
    / "visium_human_breast_cancer_clustered_labeled.h5ad"
)

# Directory where figures from this script will be saved.
FIGURE_DIR = PROJECT_ROOT / "results" / "figures" / "02b_marker_score_annotation"

# Directory where CSV tables from this script will be saved.
TABLE_DIR = PROJECT_ROOT / "results" / "tables"

# Create output directories if they do not already exist.
FIGURE_DIR.mkdir(parents=True, exist_ok=True)
TABLE_DIR.mkdir(parents=True, exist_ok=True)


# ---------------------------------------------------------------------
# Dataset and clustering metadata
# ---------------------------------------------------------------------
# This library ID should match the key stored in `adata.uns["spatial"]`.
# Scanpy uses this ID to find the associated Visium image and scalefactors.
LIBRARY_ID = "Visium_Human_Breast_Cancer"

# Cluster column generated by the Leiden clustering step.
# If you later run Leiden at a different resolution, update this key.
CLUSTER_KEY = "leiden_r06"


# ---------------------------------------------------------------------
# Marker gene sets
# ---------------------------------------------------------------------
# These marker sets are intentionally simple and interpretable.
# They are used to generate per-spot signature scores.
#
# Notes:
#   - These gene sets are not exhaustive.
#   - Markers can overlap across biological states.
#   - Visium spots can contain mixtures of cell types.
#   - Scores should be interpreted as enrichment-like signals, not pure
#     cell-type proportions.
#
# Possible future improvements:
#   - Expand these marker sets using curated sources such as MSigDB,
#     PanglaoDB, CellMarker, or Azimuth references.
#   - Use a breast cancer single-cell reference to estimate cell-type
#     proportions per Visium spot.
#   - Add separate signatures for CAF subtypes, macrophage polarization,
#     cytotoxic T cells, plasma cells, hypoxia, EMT, and proliferation.
MARKER_SETS = {
    "tumor_epithelial": [
        "EPCAM",
        "KRT8",
        "KRT18",
        "KRT19",
        "MUC1",
        "KRT7",
    ],
    "stromal_caf": [
        "COL1A1",
        "COL1A2",
        "COL3A1",
        "DCN",
        "LUM",
        "ACTA2",
        "TAGLN",
    ],
    "pan_immune": [
        "PTPRC",
        "LCP1",
        "CD52",
        "CORO1A",
    ],
    "t_cell": [
        "CD3D",
        "CD3E",
        "CD2",
        "TRAC",
        "CD8A",
        "CD8B",
    ],
    "b_cell": [
        "MS4A1",
        "CD79A",
        "CD79B",
        "BANK1",
    ],
    "myeloid_macrophage": [
        "LST1",
        "C1QA",
        "C1QB",
        "C1QC",
        "CD68",
        "TYROBP",
        "FCER1G",
    ],
    "endothelial": [
        "PECAM1",
        "VWF",
        "KDR",
        "ENG",
        "PLVAP",
    ],
    "proliferation": [
        "MKI67",
        "TOP2A",
        "PCNA",
        "MCM5",
        "STMN1",
    ],
}


# Human-readable labels for the marker set names above.
# These names are used in output tables and plots.
LABEL_DISPLAY_NAMES = {
    "tumor_epithelial": "Tumor epithelial",
    "stromal_caf": "Stromal/CAF",
    "pan_immune": "Immune-enriched",
    "t_cell": "T-cell enriched",
    "b_cell": "B-cell enriched",
    "myeloid_macrophage": "Myeloid/macrophage",
    "endothelial": "Endothelial/vascular",
    "proliferation": "Proliferative",
}


def save_current_fig(filename: str) -> None:
    """
    Save the active matplotlib figure to the marker-score output folder.

    Parameters
    ----------
    filename:
        Name of the file to save inside FIGURE_DIR.

    Notes
    -----
    The figure is closed after saving to prevent plots from overlapping and
    to avoid memory buildup when running many plotting commands.
    """
    out_path = FIGURE_DIR / filename
    plt.savefig(out_path, dpi=300, bbox_inches="tight")
    plt.close()
    print(f"Saved figure: {out_path}")


def get_available_markers(adata, genes: list[str]) -> list[str]:
    """
    Return only marker genes that are present in the AnnData object.

    Parameters
    ----------
    adata:
        AnnData object containing the Visium expression matrix.

    genes:
        Candidate marker genes for a biological signature.

    Returns
    -------
    list[str]
        Marker genes present in the dataset.

    Why this check matters
    ----------------------
    Some marker genes may be absent after filtering, gene-name formatting, or
    highly variable gene subsetting. This script uses `adata.raw` when present
    because `adata.raw` usually stores the full normalized gene matrix before
    HVG subsetting.

    Alternative
    -----------
    If using Ensembl IDs instead of gene symbols, this function would need to
    map marker gene symbols to Ensembl IDs before scoring.
    """
    if adata.raw is not None:
        gene_index = set(adata.raw.var_names)
    else:
        gene_index = set(adata.var_names)

    return [gene for gene in genes if gene in gene_index]


def assign_cluster_labels(cluster_scores: pd.DataFrame) -> pd.DataFrame:
    """
    Assign preliminary biological labels to Leiden clusters.

    Parameters
    ----------
    cluster_scores:
        DataFrame where rows are Leiden clusters and columns are mean marker
        signature scores.

    Returns
    -------
    pd.DataFrame
        One row per cluster with:
            - preliminary label
            - top marker signature
            - second-best marker signature
            - score margin between top and second-best signature

    Labeling strategy
    -----------------
    This is a heuristic method:
        1. Find the highest mean marker signature score for each cluster.
        2. Use that signature as the first-pass label.
        3. Apply a few biological refinement rules.
        4. Mark clusters as mixed if the top two signatures are too close.

    Why this is useful
    ------------------
    This gives quick interpretability before formal marker-gene analysis.

    Limitations
    -----------
    - Marker scores are not cell-type proportions.
    - Visium spots can contain mixtures of cells.
    - A high signature score does not prove cell identity.
    - Some signatures may be correlated.
    - Final labels should be refined using differential expression and spatial
      marker plots.

    Alternative approaches
    ----------------------
    Other cluster labeling strategies could include:
        - manual expert annotation from marker gene tables
        - automated cell-type annotation using single-cell references
        - majority vote across multiple marker databases
        - pathway enrichment per cluster
        - probabilistic labels instead of hard labels
    """
    rows = []

    for cluster_id, row in cluster_scores.iterrows():
        # Sort marker signatures from highest to lowest for this cluster.
        sorted_scores = row.sort_values(ascending=False)

        # Highest-scoring biological signature.
        top_signature = sorted_scores.index[0]

        # Second-highest signature; useful for detecting mixed clusters.
        second_signature = sorted_scores.index[1]

        # Numeric score values for the top two signatures.
        top_score = sorted_scores.iloc[0]
        second_score = sorted_scores.iloc[1]

        # Difference between top and second-best signature.
        # Small margins suggest mixed or ambiguous biology.
        margin = top_score - second_score

        # Start with the simple label corresponding to the top signature.
        label = LABEL_DISPLAY_NAMES[top_signature]

        # ------------------------------------------------------------------
        # Biological refinement rule 1:
        # Proliferation can occur in tumor regions. If proliferation is the
        # top score and epithelial signal is also above the cluster median,
        # label it as proliferative tumor rather than generic proliferation.
        # ------------------------------------------------------------------
        if (
            top_signature == "proliferation"
            and row.get("tumor_epithelial", -999) > row.median()
        ):
            label = "Proliferative tumor"

        # ------------------------------------------------------------------
        # Biological refinement rule 2:
        # If epithelial signal is strongest and proliferation is also high,
        # flag the cluster as tumor epithelial/proliferative.
        #
        # The 75th percentile threshold is a heuristic. Alternatives include:
        #   - fixed threshold after z-scoring scores
        #   - rank-based rules
        #   - manual inspection of MKI67/TOP2A spatial plots
        # ------------------------------------------------------------------
        elif (
            top_signature == "tumor_epithelial"
            and row.get("proliferation", -999) > sorted_scores.quantile(0.75)
        ):
            label = "Tumor epithelial/proliferative"

        # ------------------------------------------------------------------
        # Biological refinement rule 3:
        # Immune-related signatures can overlap. If myeloid/macrophage signal
        # is at least as strong as broad pan-immune signal, call it
        # myeloid/immune enriched.
        # ------------------------------------------------------------------
        elif (
            top_signature in ["pan_immune", "t_cell", "b_cell", "myeloid_macrophage"]
            and row.get("myeloid_macrophage", -999) >= row.get("pan_immune", -999)
        ):
            label = "Myeloid/immune enriched"

        # ------------------------------------------------------------------
        # Ambiguity rule:
        # If the top two scores are very close, mark the cluster as mixed.
        #
        # The 0.05 cutoff is heuristic and can be tuned.
        # Possible alternatives:
        #   - use a relative margin, e.g. margin / abs(top_score)
        #   - use z-scored cluster scores
        #   - manually inspect top DE markers before assigning mixed labels
        # ------------------------------------------------------------------
        if margin < 0.05:
            label = (
                f"Mixed: {LABEL_DISPLAY_NAMES[top_signature]} / "
                f"{LABEL_DISPLAY_NAMES[second_signature]}"
            )

        # Store a compact summary for this cluster.
        rows.append(
            {
                "cluster": cluster_id,
                "preliminary_label": label,
                "top_signature": top_signature,
                "top_score": top_score,
                "second_signature": second_signature,
                "second_score": second_score,
                "score_margin": margin,
            }
        )

    return pd.DataFrame(rows)


def main() -> None:
    """
    Run preliminary marker-score annotation.

    Workflow
    --------
    1. Load clustered AnnData object.
    2. Score each marker gene set in every spot.
    3. Average marker scores by Leiden cluster.
    4. Assign preliminary biological labels to clusters.
    5. Save tables and plots.
    6. Save a new AnnData object with preliminary labels.
    """
    print(f"Loading clustered AnnData object from: {INPUT_H5AD}")

    # Load the processed clustered AnnData file from Milestone 2.
    adata = sc.read_h5ad(INPUT_H5AD)

    print("\nLoaded object:")
    print(adata)

    # Confirm that the expected Leiden cluster column is present.
    if CLUSTER_KEY not in adata.obs.columns:
        raise ValueError(f"Could not find cluster key in adata.obs: {CLUSTER_KEY}")

    # ------------------------------------------------------------------
    # 1. Score each biological marker set per spot
    # ------------------------------------------------------------------
    # Each marker signature will become a new column in `adata.obs`.
    # Example:
    #   tumor_epithelial_score
    #   stromal_caf_score
    #   pan_immune_score
    #
    # Scanpy's score_genes compares expression of the marker genes to a
    # matched set of control genes. It is useful for relative signature
    # activity, but should not be interpreted as absolute cell abundance.
    # ------------------------------------------------------------------
    score_columns = []

    for signature_name, genes in MARKER_SETS.items():
        # Keep only genes that are available in this dataset.
        available_genes = get_available_markers(adata, genes)

        print(f"\n{signature_name}")
        print(f"  Requested genes: {genes}")
        print(f"  Available genes: {available_genes}")

        # Require at least two genes so a signature is not driven by a single
        # potentially noisy marker.
        #
        # Alternative:
        #   For rare but highly specific markers, a one-gene score could be
        #   allowed, but it should be interpreted cautiously.
        if len(available_genes) < 2:
            print(f"  Skipping {signature_name}: fewer than 2 genes available.")
            continue

        # Name of the new spot-level score column.
        score_name = f"{signature_name}_score"

        # Compute marker signature score for each spot.
        sc.tl.score_genes(
            adata,
            gene_list=available_genes,
            score_name=score_name,
            use_raw=True if adata.raw is not None else False,
        )

        # Track all score columns so they can be used later for aggregation,
        # tables, and spatial plotting.
        score_columns.append(score_name)

    print("\nCreated score columns:")
    print(score_columns)

    # ------------------------------------------------------------------
    # 2. Aggregate signature scores by Leiden cluster
    # ------------------------------------------------------------------
    # Here we compute the mean marker signature score for each cluster.
    #
    # Alternative summary statistics:
    #   - median score per cluster: more robust to outliers
    #   - trimmed mean: robust while retaining some continuous signal
    #   - fraction of spots above a score threshold
    #   - z-scored mean relative to all clusters
    # ------------------------------------------------------------------
    cluster_scores = (
        adata.obs[[CLUSTER_KEY] + score_columns]
        .groupby(CLUSTER_KEY, observed=True)
        .mean()
    )

    # Make column names cleaner in output tables by removing "_score".
    cluster_scores.columns = [
        col.replace("_score", "") for col in cluster_scores.columns
    ]

    # Save cluster-level marker signature scores.
    cluster_scores.to_csv(TABLE_DIR / "cluster_marker_signature_scores.csv")

    print("\nCluster-level marker signature scores:")
    print(cluster_scores)

    # ------------------------------------------------------------------
    # 3. Assign preliminary biological labels
    # ------------------------------------------------------------------
    # This creates one suggested biological label per Leiden cluster.
    annotations = assign_cluster_labels(cluster_scores)

    # Save cluster-level preliminary annotation table.
    annotations.to_csv(
        TABLE_DIR / "preliminary_cluster_annotations.csv",
        index=False,
    )

    print("\nPreliminary cluster annotations:")
    print(annotations)

    # Convert annotation table to a mapping:
    #   cluster ID -> preliminary label
    cluster_to_label = dict(
        zip(
            annotations["cluster"].astype(str),
            annotations["preliminary_label"],
        )
    )

    # Add preliminary biological labels to every spot.
    # Since each spot belongs to a Leiden cluster, every spot receives the
    # preliminary label assigned to its cluster.
    adata.obs["preliminary_niche_label"] = (
        adata.obs[CLUSTER_KEY]
        .astype(str)
        .map(cluster_to_label)
        .astype("category")
    )

    # Create labels that include both cluster number and biological label.
    # This keeps the original cluster identity visible in plots.
    cluster_to_combined_label = {
        cluster: f"{cluster}: {label}"
        for cluster, label in cluster_to_label.items()
    }

    adata.obs["cluster_preliminary_label"] = (
        adata.obs[CLUSTER_KEY]
        .astype(str)
        .map(cluster_to_combined_label)
        .astype("category")
    )

    # Save a spot-level table containing:
    #   - Leiden cluster
    #   - preliminary niche label
    #   - combined cluster + label
    #   - marker signature scores
    #
    # This table is useful for debugging and can also be used as input to
    # downstream ML feature engineering.
    adata.obs[
        [
            CLUSTER_KEY,
            "preliminary_niche_label",
            "cluster_preliminary_label",
        ]
        + score_columns
    ].to_csv(TABLE_DIR / "spot_marker_scores_and_labels.csv")

    # ------------------------------------------------------------------
    # 4. Plot marker signature scores on the tissue
    # ------------------------------------------------------------------
    # This shows where each biological signal is spatially enriched.
    #
    # Alternative plots:
    #   - dotplot by Leiden cluster
    #   - matrixplot by Leiden cluster
    #   - violin plot by cluster
    #   - spatial neighborhood enrichment if Squidpy is available
    # ------------------------------------------------------------------
    sc.pl.spatial(
        adata,
        color=score_columns,
        library_id=LIBRARY_ID,
        show=False,
    )
    save_current_fig("spatial_marker_signature_scores.png")

    # ------------------------------------------------------------------
    # 5. Plot preliminary biological labels
    # ------------------------------------------------------------------
    # Spatial plot: shows whether preliminary labels form coherent tissue
    # regions rather than random scattered spots.
    sc.pl.spatial(
        adata,
        color=["cluster_preliminary_label"],
        library_id=LIBRARY_ID,
        show=False,
    )
    save_current_fig("spatial_clusters_with_preliminary_labels.png")

    # UMAP plot: shows whether preliminary labels are separated in expression
    # embedding space.
    sc.pl.umap(
        adata,
        color=["cluster_preliminary_label"],
        legend_loc="right margin",
        frameon=False,
        show=False,
    )
    save_current_fig("umap_clusters_with_preliminary_labels.png")

    # ------------------------------------------------------------------
    # 6. Plot cluster-level signature score heatmap
    # ------------------------------------------------------------------
    # This heatmap summarizes which marker programs are strongest in each
    # Leiden cluster.
    #
    # Alternative:
    #   Use seaborn.clustermap for hierarchical clustering of signatures and
    #   clusters. This script avoids seaborn clustering to keep dependencies
    #   and interpretation simple.
    # ------------------------------------------------------------------
    fig, ax = plt.subplots(figsize=(10, 6))

    # Plot cluster-by-signature matrix.
    im = ax.imshow(cluster_scores.values, aspect="auto")

    # X-axis: marker signatures.
    ax.set_xticks(range(cluster_scores.shape[1]))
    ax.set_xticklabels(cluster_scores.columns, rotation=45, ha="right")

    # Y-axis: Leiden cluster IDs.
    ax.set_yticks(range(cluster_scores.shape[0]))
    ax.set_yticklabels(cluster_scores.index)

    ax.set_xlabel("Marker signature")
    ax.set_ylabel("Leiden cluster")
    ax.set_title("Mean marker signature score by Leiden cluster")

    fig.colorbar(im, ax=ax, label="Mean signature score")
    save_current_fig("cluster_marker_signature_score_heatmap.png")

    # ------------------------------------------------------------------
    # 7. Save updated AnnData object
    # ------------------------------------------------------------------
    # This file preserves the original clustered object plus:
    #   - marker signature score columns
    #   - preliminary niche labels
    #   - combined cluster + preliminary label column
    #
    # Later scripts can load this file instead of recomputing the labels.
    adata.write_h5ad(OUTPUT_H5AD)

    print(f"\nSaved labeled AnnData object to: {OUTPUT_H5AD}")
    print("\nMilestone 2.5 complete.")


if __name__ == "__main__":
    main()
